const KEYS = {
  row1: [
    { id: 'Backquote',     type: 'symbol',      value: { en: ['`', '~'], ru: ['ё', 'Ё'] } },
    { id: 'Digit1',        type: 'symbol',      value: { en: ['1', '!'], ru: ['1', '!'] } },
    { id: 'Digit2',        type: 'symbol',      value: { en: ['2', '@'], ru: ['2', '"'] } },
    { id: 'Digit3',        type: 'symbol',      value: { en: ['3', '#'], ru: ['3', '№'] } },
    { id: 'Digit4',        type: 'symbol',      value: { en: ['4', '$'], ru: ['4', ';'] } },
    { id: 'Digit5',        type: 'symbol',      value: { en: ['5', '%'], ru: ['5', '%'] } },
    { id: 'Digit6',        type: 'symbol',      value: { en: ['6', '^'], ru: ['6', '?'] } },
    { id: 'Digit7',        type: 'symbol',      value: { en: ['7', '&'], ru: ['7', '?'] } },
    { id: 'Digit8',        type: 'symbol',      value: { en: ['8', '*'], ru: ['8', '*'] } },
    { id: 'Digit9',        type: 'symbol',      value: { en: ['9', '('], ru: ['9', '('] } },
    { id: 'Digit0',        type: 'symbol',      value: { en: ['0', ')'], ru: ['0', ')'] } },
    { id: 'Minus',         type: 'symbol',      value: { en: ['-', '_'], ru: ['-', '_'] } },
    { id: 'Equal',         type: 'symbol',      value: { en: ['=', '+'], ru: ['=', '+'] } },
    { id: 'Backspace',     type: 'special',     value: 'Backspace' },
  ],

  row2: [
    { id: 'Tab',           type: 'special',     value: 'Tab' },
    { id: 'KeyQ',          type: 'symbol',      value: { en: ['q', 'Q'], ru: ['й', 'Й'] } },
    { id: 'KeyW',          type: 'symbol',      value: { en: ['w', 'W'], ru: ['ц', 'Ц'] } },
    { id: 'KeyE',          type: 'symbol',      value: { en: ['e', 'E'], ru: ['у', 'У'] } },
    { id: 'KeyR',          type: 'symbol',      value: { en: ['r', 'R'], ru: ['к', 'К'] } },
    { id: 'KeyT',          type: 'symbol',      value: { en: ['t', 'T'], ru: ['е', 'Е'] } },
    { id: 'KeyY',          type: 'symbol',      value: { en: ['y', 'Y'], ru: ['н', 'Н'] } },
    { id: 'KeyU',          type: 'symbol',      value: { en: ['u', 'U'], ru: ['г', 'Г'] } },
    { id: 'KeyI',          type: 'symbol',      value: { en: ['i', 'I'], ru: ['ш', 'Ш'] } },
    { id: 'KeyO',          type: 'symbol',      value: { en: ['o', 'O'], ru: ['щ', 'Щ'] } },
    { id: 'KeyP',          type: 'symbol',      value: { en: ['p', 'P'], ru: ['з', 'З'] } },
    { id: 'BracketLeft',   type: 'symbol',      value: { en: ['[', '{'], ru: ['х', 'Х'] } },
    { id: 'BracketRight',  type: 'symbol',      value: { en: [']', '}'], ru: ['ъ', 'Ъ'] } },
    { id: 'Delete',        type: 'special',     value: 'Delete' },
  ],

  row3: [
    { id: 'CapsLock',      type: 'special',     value: 'CapsLock' },
    { id: 'KeyA',          type: 'symbol',      value: { en: ['a', 'A'], ru: ['ф', 'Ф'] } },
    { id: 'KeyS',          type: 'symbol',      value: { en: ['s', 'S'], ru: ['ы', 'Ы'] } },
    { id: 'KeyD',          type: 'symbol',      value: { en: ['d', 'D'], ru: ['в', 'В'] } },
    { id: 'KeyF',          type: 'symbol',      value: { en: ['f', 'F'], ru: ['а', 'А'] } },
    { id: 'KeyG',          type: 'symbol',      value: { en: ['g', 'G'], ru: ['п', 'П'] } },
    { id: 'KeyH',          type: 'symbol',      value: { en: ['h', 'H'], ru: ['р', 'Р'] } },
    { id: 'KeyJ',          type: 'symbol',      value: { en: ['j', 'J'], ru: ['о', 'О'] } },
    { id: 'KeyK',          type: 'symbol',      value: { en: ['k', 'K'], ru: ['л', 'Л'] } },
    { id: 'KeyL',          type: 'symbol',      value: { en: ['l', 'L'], ru: ['д', 'Д'] } },
    { id: 'Semicolon',     type: 'symbol',      value: { en: [';', ':'], ru: ['ж', 'Ж'] } },
    { id: 'Quote',         type: 'symbol',      value: { en: ["'", '"'], ru: ['э', 'Э'] } },
    { id: 'Enter',         type: 'special',     value: 'Enter' },
  ],

  row4: [
    { id: 'ShiftLeft',     type: 'special',     value: 'Shift' },
    { id: 'Backslash',     type: 'symbol',      value: { en: ['\\', '|'], ru: ['\\', '/'] } },
    { id: 'KeyZ',          type: 'symbol',      value: { en: ['z', 'Z',], ru: ['я', 'Я'] } },
    { id: 'KeyX',          type: 'symbol',      value: { en: ['x', 'X',], ru: ['ч', 'Ч'] } },
    { id: 'KeyC',          type: 'symbol',      value: { en: ['c', 'C',], ru: ['с', 'С'] } },
    { id: 'KeyV',          type: 'symbol',      value: { en: ['v', 'V',], ru: ['м', 'М'] } },
    { id: 'KeyB',          type: 'symbol',      value: { en: ['b', 'B',], ru: ['и', 'И'] } },
    { id: 'KeyN',          type: 'symbol',      value: { en: ['n', 'N',], ru: ['т', 'Т'] } },
    { id: 'KeyM',          type: 'symbol',      value: { en: ['m', 'M',], ru: ['ь', 'Ь'] } },
    { id: 'Comma',         type: 'symbol',      value: { en: [',', ',',], ru: ['б', 'Б'] } },
    { id: 'Period',        type: 'symbol',      value: { en: ['.', '.',], ru: ['ю', 'Ю'] } },
    { id: 'Slash',         type: 'symbol',      value: { en: ['/', '?',], ru: ['.', ','] } },
    { id: 'ArrowUp',       type: 'arrow',       value: '▲' },
    { id: 'ShiftRight',    type: 'special',     value: 'Shift' },
  ],

  row5: [
    { id: 'ControlLeft',   type: 'special',     value: 'Ctrl' },
    { id: 'Win',           type: 'special',     value: 'Win' },
    { id: 'AltLeft',       type: 'special',     value: 'Alt' },
    { id: 'Space',         type: 'symbol',      value: ' ' },
    { id: 'AltRight',      type: 'special',     value: 'Alt' },
    { id: 'ControlRight',  type: 'special',     value: 'Ctrl' },
    { id: 'ArrowLeft',     type: 'arrow',       value: '◄' },
    { id: 'ArrowDown',     type: 'arrow',       value: '▼' },
    { id: 'ArrowRight',    type: 'arrow',       value: '►' },
  ]
}

export default KEYS
